/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package haarfiltervertical;

/**
 *
 * @author user
 */
public class Features {

    /**
     * The FeatureA function produces a sliding window and generates a position
     * to lay down the window for further calculations
     */
    public void FeatureA() {
        int imgH = 5;
        int imgW = 5;
        int count = 0;
        int[][] integralValues = new int[5][5];
        /**
         * Image area is a class to calculate the area of a certain window
         * generated by the i and j values in the following loop and sliding it
         * through each position of the array which will later be replaced by an
         * image to calculate its features
         */
        ImageArea imageArea = new ImageArea();

        int w = 1, h = 2;
        for (int i = 1; i <= (imgH / h); i++) {
            for (int j = 1; j <= (imgW / w); j++) {
                for (int x = 1; x <= (imgH - i * h + 1); x++) {
                    for (int y = 1; y <= imgW - j * w + 1; y++) {
                        /**
                         * CalculateArea gives the area of the selected window
                         * with reference to the integral image and drastically
                         * reduces the computation time
                         */
                        imageArea.CalculateArea(j, i, y, x, count);
                        count++;
                    }
                }
//                System.out.println("");
//                System.out.println("COUNT= " + count);
            }
        }
    }

}
